// Generated by CoffeeScript 1.6.2
"use strict";
var AWSTask, fs, glob, path, requiredir, subtasks;

glob = require("glob-manifest");

fs = require("fs");

path = require("path");

requiredir = require("require-dir");

subtasks = requiredir("./subtasks");

console.log(subtasks);

AWSTask = (function() {
  AWSTask.prototype.defaults = {
    punctuation: ".",
    separator: ", "
  };

  function AWSTask(grunt, task) {
    this.grunt = grunt;
    this.task = task;
    this.name = this.task.target;
    this.opts = this.task.options(this.defaults);
    this.data = this.task.data;
    this.done = this.task.async();
    this.run();
  }

  AWSTask.prototype.run = function() {
    console.log("running");
    console.log(this.task);
    glob(this.data.files, function(err, files) {
      if (err) {
        throw err;
      }
      return console.log(files);
    });
    return this.done();
  };

  return AWSTask;

})();

module.exports = function(grunt) {
  return grunt.registerMultiTask("aws", "A Grunt interface into the Amazon Node.JS SDK", function() {
    return new AWSTask(grunt, this);
  });
};
