// Generated by CoffeeScript 1.6.2
var AWS, BaseService;

AWS = require("aws-sdk");

BaseService = (function() {
  function BaseService() {
    this.foo = 42;
  }

  return BaseService;

})();

module.exports = BaseService;
